accounts:
  - name: MOONBYS-I
    coins: ["250000000pan", "250000000000000upan"]
validator:
  name: MOONBYS-I
  staked: "100000000000000upan"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: MOONBYS-I
  coins: ["50000000pan", "500000000upan"]
build:
  binary: "moonbys"
  moniker: "MOONBYS-I"
genesis:
  chain_id: "pan-chain"
  moniker: "MOONBYS-I"
  app_state:
    staking:
      params:
        bond_denom: "upan"
    gov:
      deposit_params:
        min_deposit:
          - denom: pan
            amount: "200"
        max_deposit_period: "604800s"
init:
  client:
    keyring-backend: "os"
